version: '3.4'

networks:
    net:
      external:
        name: net

services:
  node_server:
    hostname: nodeServer.org1.example.com
    image: hlf/node-server:latest
    working_dir: /usr/src/app
    depends_on:
      - orderer0.ordererOrg1.example.com
      - orderer1.ordererOrg1.example.com
      - orderer0.ordererOrg2.example.com
      - orderer1.ordererOrg2.example.com
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer0.org2.example.com
      - peer1.org2.example.com
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
          condition: on-failure
      placement:
            constraints:
              - node.hostname == maurice-mobile
    networks:
      net:
        aliases:
          - nodeServer.org1.example.com
    ports:
      - 3000:3000
