version: '3.4'

networks:
    net:
      external:
        name: net

services:
  node_server:
    hostname: nodeServer.org1.example.com
    image: hlf/node-server:latest
    working_dir: /usr/src/app
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
      - DISCOVERY_AS_LOCALHOST=false
      - CORE_O1_ENDPOINT=10.0.0.209
      - CORE_O2_ENDPOINT=10.0.0.211
      - CORE_O3_ENDPOINT=10.0.0.115
      - CORE_O4_ENDPOINT=10.0.0.117
    depends_on:
      - orderer0.ordererOrg1.example.com
      - orderer1.ordererOrg1.example.com
      - orderer0.ordererOrg2.example.com
      - orderer1.ordererOrg2.example.com
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer0.org2.example.com
      - peer1.org2.example.com
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
          condition: on-failure
      placement:
            constraints:
              - node.hostname == hlf-server1
    networks:
      net:
        aliases:
          - nodeServer.org1.example.com
    ports:
      - 3000:3000
